### ISSUE TITLE
ThrustNav: Still Spinning message delay causes confusion

### ISSUE THREAD

**Issue by davecparker** [davecparker/mars-app#107]
The "Still Spinning" message with wait for dismiss before going to mainAct makes the back button seem either broken or ignored. So then you start playing the game again, and then get suddenly taken back a couple of seconds later. Should probably transition right away then let the message show on the mainAct screen. Or...

Or an alternative would be to send a new text message, which might feel and also look better. You can define new text messages in msgText.lua then send with game.sendMessage( id ). You could do this in gameState.lua in an else clause for the test: if ss.thrustNav.onTarget then... 

You can assign this back to me if you want me to do this instead.

**Comment by electriccord** [comment]
Latest pull request fixes this.  12/3/2015 at 11am.
Makes back button immediate and "Spinning" message last 3 seconds over ship view.
Cord
