### ISSUE TITLE
Running out of energy doesn't matter

### ISSUE THREAD

**Issue by davecparker** [davecparker/mars-app#109]
Not sure if anything checks or cares if you run out of energy

**Comment by davecparker** [comment]
For now in this version, the only consequence of running out of energy is that the rover must return to the ship (where it will recharge). Also can't drill for water. Can you detect this, then:
1. Display message
2. Auto-plot course back to ship and don't let the user change it
3. Disable link to drill scan
We can say the rover returns to base on "reserve" power.
Perhaps limit max speed when on reserve power.

**Comment by davecparker** [comment]
Also need a battery level (energy) display in rover.

**Comment by MichaelFriebel** [comment]
This has been implemented with pull request #177. I will open a new issue for the enhancement of the energy display since it's functional but minimal.
