### ISSUE TITLE
Door lock: Title bar slightly covered on iPad/iPhone4

### ISSUE THREAD

**Issue by davecparker** [davecparker/mars-app#118]
On wide aspect devices (iPad), the door lock visuals cover up the title bar, which has the room name.

**Comment by davecparker** [comment]
iPad now shows side bars to match iPhone 4 aspect, so now you only need to tweak the coordinates to lower everything a bit so it fits on iPhone 4.

**Comment by RyanBJ** [comment]
As of the 27th, the key pad and screen in the door lock act have been adjusted to fit in the act area properly.
