### ISSUE TITLE
App needs a name

### ISSUE THREAD

**Issue by davecparker** [davecparker/mars-app#163]
Need to replace "Mars App" with a real app name in the About screen, etc.

**Comment by davecparker** [comment]
Suggestions that don't appear to be taken:
Mars Explorer
Mars Mission Sierra
Mars Mystery

**Comment by JoeCracchiolo** [comment]
I got a suggestion that's not taken
Mars Unknown

**Comment by MichaelFriebel** [comment]
Here's a brainstorm. Some are definitely ill-fitting but may spawn ideas. All seem available. 

Mars Lost
Mission Sierra: Mars Lost
Mars: First Landing 
Escape to Mars
Mission Sierra: The Vanishing 
Mars Forlorn 
Mars Proximate
Mars Imminent 
Mars Ephemeral 
Mars Anomalous 
Mars Ominous 
The Martian Anomaly 
Martian Terror
Terror in the Martian Sky
In the Martian Darkness 
Red Gloom
Red Planet Mystery
Chasing Mars
Mars Bound
Mission Sierra: Ghostship
The Martian Ghostship 
Ghostship to Mars
Martian Menace
Martian Vengeance
Martian Mystique
Martian Solitaire 
Martian Invader
The Revenge of Mars
Vengeful Mars

**Comment by electriccord** [comment]
Mars Mission Mayhem

**Comment by davecparker** [comment]
Lots of great ideas, thanks!
I do want to keep the core app name to two words so the launcher icon can show it.
So I think for now we will go with "Mars Explorer", and perhaps in the game itself we could maybe add a subtitle such as "Spaceship Sierra" or something if we want.

**Comment by davecparker** [comment]
About screen now includes title "Mars Explorer". Device builds can be given this name in the Build dialog.
