### ISSUE TITLE
Background sounds continues

### ISSUE THREAD

**Issue by arshiahf** [davecparker/mars-app#167]
If you go to the settings screen before leaving any given screen with background sounds, the sounds will continue as you go anywhere else. Sounds are replaced any time you enter a location with its own background sounds. Wouldn't be much of a problem on the release version, as users don't have access to the debug screen, but may cause some issues down the line.

**Comment by davecparker** [comment]
This is by design in general: Any existing ambient sound should carry over into Settings, Messages, and Documents. If you then enter a new act that needs to select its own ambient sound, it needs to do so. I will review to makes sure the major acts are doing this.

**Comment by davecparker** [comment]
Reviewed ambient sounds. It's by design that ambient sounds continue when reading messages, etc., with one exception: drill engine idle stops. Changed shipLanding sound to continue.
