### ISSUE TITLE
Rover: Getting back to ship is hard and inconsistent

### ISSUE THREAD

**Issue by davecparker** [davecparker/mars-app#94]
Getting back to the ship from the rover seems too hard (ship hit area too small?) and maybe buggy. One user saw that zooming out the map would suddenly put you back in the ship when close.

**Comment by MichaelFriebel** [comment]
This has been fixed as of pull request #177. However, there remains a very slight and momentary irregularity in the distance-from-ship calculation during the simultaneous map scaling and tracking dot movement transitions that occur when the map is both scaled and panned. It only affects return-to-ship functionality when the rover is located 2.000-2.015 Corona units from the ship and the user zooms to the original map scale, or when the rover is located 1.985-2.000 Corona units from the ship and the user zooms from the original map scale. I think the current issue can be closed but I will open a new issue for this remaining bug.
